#!/usr/bin/env python3
"""Convert the MAME 'frogger' ROM set into a C header for RIBBIT.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)

Two of the ROMs come off the board with data lines D0 and D1 swapped - the first
sound ROM and the second graphics ROM. MAME undoes that at load time; we do it
here so the emulator never has to think about it.
"""
import sys, zlib
from pathlib import Path

MAIN  = [('frogger.26', 0x1000), ('frogger.27', 0x1000), ('frsm3.7', 0x1000)]
AUDIO = [('frogger.608', 0x800), ('frogger.609', 0x800), ('frogger.610', 0x800)]
GFX   = [('frogger.607', 0x800), ('frogger.606', 0x800)]
PROM  =  ('pr-91.6l', 0x20)

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def swap_d0_d1(data):
    return bytes((b & 0xfc) | ((b & 1) << 1) | ((b >> 1) & 1) for b in data)

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'frogger')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    main_rom = b''.join(load(romdir, n, s) for n, s in MAIN)
    audio = [load(romdir, n, s) for n, s in AUDIO]
    audio[0] = swap_d0_d1(audio[0])          # the first sound ROM has D0 and D1 swapped
    audio_rom = b''.join(audio)
    gfx = [load(romdir, n, s) for n, s in GFX]
    gfx[1] = swap_d0_d1(gfx[1])              # so does the second graphics ROM
    gfx_rom = b''.join(gfx)
    prom = load(romdir, PROM[0], PROM[1])
    out = ['/* frogger_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef FROGGER_ROMS_H', '#define FROGGER_ROMS_H', '#include <stdint.h>', '',
           '/* main CPU, 0x0000-0x2FFF */', c_array('fr_rom', main_rom, '[0x3000]'), '',
           '/* sound CPU, 0x0000-0x17FF (first 2K de-scrambled) */', c_array('fr_audiorom', audio_rom, '[0x1800]'), '',
           '/* character and sprite planes (second half de-scrambled) */', c_array('fr_gfx', gfx_rom, '[0x1000]'), '',
           '/* colour PROM */', c_array('fr_prom', prom, '[0x20]'), '',
           '#endif']
    (outdir / 'frogger_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "frogger_roms.h"}')

if __name__ == '__main__':
    main()
